"""Add unique constraint for payment period

Revision ID: f95f0878e106
Revises: 2a26920183b3
Create Date: 2026-01-09 11:11:35.347595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95f0878e106'
down_revision: Union[str, Sequence[str], None] = '2a26920183b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_payment_period', 'payments', ['subscription_id', 'paid_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payment_period', 'payments', type_='unique')
    # ### end Alembic commands ###
